# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_0', models.CharField(max_length=100)),
                ('field_1', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
